language: python
python:
  - "3.7"
  - "3.8"

before_install:
  # Install the latest version of Miniconda
  # -O writes the file to minoconda.sh
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  # b—Batch mode with no PATH modifications to ~/.bashrc. Assumes that you agree to the license agreement. Does not edit the .bashrc or .bash_profile files.
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda  # Update CONDA without command line prompt
  # Useful for debugging any issues with conda
  - conda info -a

install:
  - conda create -n autometa python=$TRAVIS_PYTHON_VERSION
  - conda install -n autometa -c bioconda -c conda-forge --yes \
      biopython \
      pandas \
      tqdm \
      tsne \
      numpy \
      scikit-learn \
      scikit-bio \
      samtools \
      bedtools \
      bowtie2 \
      hmmer \
      prodigal \
      ndcctools \
      parallel \
      requests \
      umap-learn \
      hdbscan \
      pytest \
      pytest-cov \
      pytest-html \
      pytest-repeat \
      pytest-variables \
      codecov \
      pip \
      && conda clean --all --yes
  - pip install pytest-md pytest-emoji
  - conda activate autometa

# command to run tests
script:
  - make test
after_success:
    - codecov # submit coverage report to codecov.io
